import { Poppins } from "next/font/google";
import "../sass/main.scss";
import { ThemeProvider, useThemeContext } from "@/context/ThemeContext";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import PageSkinLeft from "@/components/ads/adsComponents/PageSkinLeft";
import { AdsContextProvider } from "@/context/AdsContext";
import PageSkinRight from "@/components/ads/adsComponents/PageSkinRight";
import LogoNext from "@/components/ads/adsComponents/LogoNext";
// import MiniNavbar from '@/components/miniNavbar/MiniNavbar';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Last Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <ThemeProvider>
          <Navbar />
          {/* <MiniNavbar /> */}
          <AdsContextProvider>
          <LogoNext />
          <div className="wholePageWrapper">
            <div className="leftPageWrapper"><PageSkinLeft /></div>
            <div className="centerPageWrapper"> {children} </div>
            <div className="rightPageWrapper"><PageSkinRight /></div>
          </div>
          </AdsContextProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
};
